test_that("ungrouped counts preserve categories and exact column order", {
  x <- freq_tbl(small_data(), outcome)
  expect_identical(names(x), c("outcome", "n", "prop"))
  expect_identical(x$outcome, c("no", "yes"))
  expect_identical(x$n, c(7L, 9L))
  expect_equal(x$prop, c(7, 9) / 16)
  expect_s3_class(x, "freq_tbl")
  expect_false(dplyr::is_grouped_df(x))
  expect_identical(freq_tbl(mtcars, "am")$n, c(19L, 13L))
  wrapper <- function(data, var) freq_tbl(data, {{ var }})
  expect_equal(wrapper(mtcars, am), freq_tbl(mtcars, am))
})

test_that("group denominators and all grouping columns are respected", {
  x <- small_data() |> dplyr::group_by(group) |> freq_tbl(outcome)
  expect_identical(names(x), c("group", "outcome", "n", "n_group", "prop_group"))
  expect_identical(x$n, c(3L, 7L, 4L, 2L))
  expect_identical(x$n_group, c(10L, 10L, 6L, 6L))
  expect_equal(x$prop_group, c(3/10, 7/10, 4/6, 2/6))
  expect_false(dplyr::is_grouped_df(x))
  expect_equal(as.numeric(tapply(x$prop_group, x$group, sum)), c(1, 1))

  d <- transform(small_data(), band = rep(c("young", "old"), 8),
                 site = rep(c("east", "west", "east", "west"), 4))
  z <- d |> dplyr::group_by(group, band, site) |> freq_tbl(outcome)
  reference <- as.data.frame(table(d$group, d$band, d$site, d$outcome))
  reference <- reference[reference$Freq > 0, ]
  key <- function(...) paste(..., sep = "/")
  idx <- match(key(z$group, z$band, z$site, z$outcome),
               key(reference$Var1, reference$Var2, reference$Var3, reference$Var4))
  expect_equal(z$n, reference$Freq[idx])
  expect_identical(names(z)[1:4], c("group", "band", "site", "outcome"))
  expect_equal(as.numeric(tapply(z$prop_group,
    interaction(z$group, z$band, z$site, drop = TRUE), sum)), rep(1, 4))
})

test_that("overall cells, display scale, and generic headers are explicit", {
  d <- small_data() |> dplyr::group_by(group)
  x <- freq_tbl(d, outcome, overall = TRUE)
  expect_equal(x$n_total, rep(16L, 4))
  expect_equal(x$prop_total, c(3, 7, 4, 2) / 16)
  pct <- freq_tbl(d, outcome, percent = TRUE, overall = TRUE)
  expect_equal(pct$percent_group, x$prop_group * 100)
  expect_equal(pct$percent_total, x$prop_total * 100)
  expect_false(any(grepl("^prop", names(pct))))
  one <- freq_tbl(small_data(), outcome, overall = TRUE, percent = TRUE)
  expect_identical(names(one), c("outcome", "n", "percent", "n_total"))
  generic <- freq_tbl(d, outcome, generic_col_names = TRUE)
  expect_identical(names(generic), c("group_01_col", "group_01_cat",
                                    "col", "cat", "n", "n_group", "prop_group"))
  expect_equal(generic$group_01_col, rep("group", 4))
  expect_equal(generic$col, rep("outcome", 4))
  stacked <- dplyr::bind_rows(freq_tbl(mtcars, am, generic_col_names = TRUE),
                              freq_tbl(small_data(), outcome,
                                       generic_col_names = TRUE))
  expect_identical(stacked$cat, c("0", "1", "no", "yes"))
  multiple <- mtcars |> dplyr::group_by(cyl, vs) |>
    freq_tbl(am, generic_col_names = TRUE)
  expect_true(all(c("group_02_col", "group_02_cat") %in% names(multiple)))
})

test_that("missing values, unused factors, and empty denominators are intentional", {
  d <- data.frame(g = factor(c("A", "A", NA), levels = c("A", "B")),
                  y = factor(c("no", NA, "yes"), levels = c("no", "yes", "unused")))
  one <- freq_tbl(d, y)
  expect_equal(one$n, c(1L, 1L, 0L, 1L))
  expect_equal(one$prop, c(1/3, 1/3, 0, 1/3))
  expect_true(is.factor(one$y))
  grouped <- d |> dplyr::group_by(g) |> freq_tbl(y)
  expect_true(anyNA(grouped$g))
  expect_true(all(grouped$n[grouped$g %in% "B"] == 0))
  expect_true(all(is.na(grouped$prop_group[grouped$g %in% "B"])))
  dropped <- d |> dplyr::group_by(g, .drop = FALSE) |> freq_tbl(y, drop = TRUE)
  expect_equal(nrow(dropped), 3)
  expect_true(anyNA(dropped$y))
  filtered <- d |> dplyr::filter(!is.na(g), !is.na(y)) |> freq_tbl(y, drop = TRUE)
  expect_identical(filtered$n, 1L)
  expect_equal(filtered$prop, 1)
  empty <- freq_tbl(d[FALSE, ], y)
  expect_equal(empty$n, c(0L, 0L, 0L))
  expect_true(all(is.na(empty$prop)))
  expect_equal(nrow(freq_tbl(data.frame(y = character()), y)), 0)
})

test_that("invalid and ambiguous calls fail before changing counts", {
  expect_error(freq_tbl(1:3, y), "data frame")
  expect_error(freq_tbl(mtcars), "requires one column")
  expect_error(freq_tbl(mtcars, missing_column), "not in .data")
  expect_error(freq_tbl(mtcars, am, cyl), "group_by")
  expect_error(freq_tbl(mtcars, am, .percent = TRUE), "named options")
  expect_error(freq_tbl(mtcars, am, percent = 1), "TRUE or FALSE")
  expect_error(freq_tbl(mtcars, am, drop = NA), "TRUE or FALSE")
  expect_error(freq_tbl(mtcars, am + 1), "existing column")
  expect_error(mtcars |> dplyr::group_by(am) |> freq_tbl(am), "grouping variable")
  expect_error(mtcars |> dplyr::rowwise() |> freq_tbl(am), "Rowwise")
  expect_error(freq_tbl(data.frame(n = 1:3), n), "Rename")
  d <- data.frame(y = c("a", "a", "b"), n = c(10, 20, 30))
  expect_equal(freq_tbl(d, y)$n, c(2L, 1L))
  names(d) <- c("y", "y")
  expect_error(freq_tbl(d, y), "unique")
  expect_error(freq_tbl(mtcars, am, overall = c(TRUE, FALSE)), "TRUE or FALSE")
  expect_error(freq_tbl(mtcars, am, generic_col_names = "yes"), "TRUE or FALSE")
})
